[build]
  command = "npm run build"
  functions = "lambda"
  publish = "dist"

[[redirects]]
  from = "/api"
  to = "http://gmall-h5-api.atguigu.cn"
  status = 200
  force = true
  headers = {X-From = "Netlify"}